services:
  - type: web
    name: horizon
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn horizweb.wsgi
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: horizon-db
          property: connectionString
      - key: DEBUG
        value: False
      - key: EMAIL_PASSWORD
        value: твой_пароль_от_почты
databases:
  - name: horizon-db
    plan: free
