# Generated by Django 5.2 on 2025-05-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_activation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Код активации'),
        ),
    ]
