# Generated by Django 5.2 on 2025-05-05 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_activation_code'),
    ]

    operations = [
    ]
